-- =============================================================================
-- Migration 00005: Driver Applications + Driver Alerts
-- Purpose: Driver registration workflow (pending → approved/rejected) and
--          system-generated alert events (speed violations, route deviations).
-- =============================================================================

-- ── driver_applications ───────────────────────────────────────────────────────
CREATE TABLE public.driver_applications (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  license_number  text        NOT NULL,
  vehicle_model   text,
  plate_number    text,
  -- Array of Supabase Storage object paths for uploaded documents
  documents_urls  text[]      NOT NULL DEFAULT '{}',
  status          text        NOT NULL DEFAULT 'pending'
                              CONSTRAINT driver_app_status_check
                              CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by     uuid        REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at     timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_driver_apps_user_id ON public.driver_applications(user_id);
CREATE INDEX idx_driver_apps_status  ON public.driver_applications(status);

-- ── driver_alerts ─────────────────────────────────────────────────────────────
-- Generated by the driver app or server-side logic when anomalies are detected.
CREATE TABLE public.driver_alerts (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id   uuid        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  bus_id      uuid        REFERENCES public.buses(id)  ON DELETE SET NULL,
  trip_id     uuid        REFERENCES public.trips(id)  ON DELETE SET NULL,
  type        text        NOT NULL
                          CONSTRAINT alert_type_check
                          CHECK (type IN (
                            'speed_violation',
                            'route_deviation',
                            'late_arrival',
                            'maintenance'
                          )),
  resolved    boolean     NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_driver_alerts_driver_id ON public.driver_alerts(driver_id);
CREATE INDEX idx_driver_alerts_resolved  ON public.driver_alerts(resolved);
CREATE INDEX idx_driver_alerts_created   ON public.driver_alerts(created_at DESC);
